/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./views/Settings/About.vue')['default']
    BookCard: typeof import('./components/BookCard.vue')['default']
    BookCardGrid: typeof import('./components/BookCardGrid.vue')['default']
    BookCardSlider: typeof import('./components/BookCardSlider.vue')['default']
    Comic: typeof import('./views/Comic.vue')['default']
    ComicPanel: typeof import('./components/ComicPanel.vue')['default']
    ComicReader: typeof import('./components/ComicReader.vue')['default']
    DefaultSidebar: typeof import('./components/Sidebar/DefaultSidebar.vue')['default']
    Epub: typeof import('./components/Epub.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Home: typeof import('./views/Home.vue')['default']
    Library: typeof import('./views/Library.vue')['default']
    Login: typeof import('./views/Login.vue')['default']
    Main: typeof import('./views/Main.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    Novel: typeof import('./views/Novel.vue')['default']
    NovelPanel: typeof import('./components/NovelPanel.vue')['default']
    NPagination: typeof import('naive-ui')['NPagination']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NProgress: typeof import('naive-ui')['NProgress']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Pagination: typeof import('./components/Pagination.vue')['default']
    RecentlyRead: typeof import('./views/RecentlyRead.vue')['default']
    RecentlyUpdated: typeof import('./views/RecentlyUpdated.vue')['default']
    Register: typeof import('./views/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Series: typeof import('./views/Series.vue')['default']
    Settings: typeof import('./views/Settings/Settings.vue')['default']
    SettingsSidebar: typeof import('./components/Sidebar/SettingsSidebar.vue')['default']
    Sidebar: typeof import('./components/Sidebar/Sidebar.vue')['default']
    SidebarMenuItem: typeof import('./components/Sidebar/SidebarMenuItem.vue')['default']
    Tasks: typeof import('./views/Tasks.vue')['default']
    User: typeof import('./views/Settings/User.vue')['default']
    UserManage: typeof import('./views/Settings/UserManage.vue')['default']
  }
}
